// x: 0=izq → 1=der  |  y: 0=arriba(rival) → 1=abajo(portería propia)
export const FORMATIONS = {
  '4-3-3': {
    slots: [
      { id: 'GK',   label: 'PO',  position: 'GK',  x: 0.50, y: 0.87 },
      { id: 'LB',   label: 'LI',  position: 'LB',  x: 0.12, y: 0.69 },
      { id: 'CB1',  label: 'DFC', position: 'CB',  x: 0.35, y: 0.71 },
      { id: 'CB2',  label: 'DFC', position: 'CB',  x: 0.65, y: 0.71 },
      { id: 'RB',   label: 'LD',  position: 'RB',  x: 0.88, y: 0.69 },
      { id: 'LCM',  label: 'MC',  position: 'CM',  x: 0.22, y: 0.48 },
      { id: 'CM',   label: 'MC',  position: 'CM',  x: 0.50, y: 0.45 },
      { id: 'RCM',  label: 'MC',  position: 'CM',  x: 0.78, y: 0.48 },
      { id: 'LW',   label: 'EI',  position: 'LW',  x: 0.12, y: 0.20 },
      { id: 'ST',   label: 'DC',  position: 'ST',  x: 0.50, y: 0.13 },
      { id: 'RW',   label: 'ED',  position: 'RW',  x: 0.88, y: 0.20 },
    ],
  },
  '4-4-2': {
    slots: [
      { id: 'GK',   label: 'PO',  position: 'GK',  x: 0.50, y: 0.87 },
      { id: 'LB',   label: 'LI',  position: 'LB',  x: 0.12, y: 0.70 },
      { id: 'CB1',  label: 'DFC', position: 'CB',  x: 0.35, y: 0.72 },
      { id: 'CB2',  label: 'DFC', position: 'CB',  x: 0.65, y: 0.72 },
      { id: 'RB',   label: 'LD',  position: 'RB',  x: 0.88, y: 0.70 },
      { id: 'LM',   label: 'MI',  position: 'LM',  x: 0.12, y: 0.50 },
      { id: 'LCM',  label: 'MC',  position: 'CM',  x: 0.37, y: 0.47 },
      { id: 'RCM',  label: 'MC',  position: 'CM',  x: 0.63, y: 0.47 },
      { id: 'RM',   label: 'MD',  position: 'RM',  x: 0.88, y: 0.50 },
      { id: 'ST1',  label: 'DC',  position: 'ST',  x: 0.35, y: 0.15 },
      { id: 'ST2',  label: 'DC',  position: 'ST',  x: 0.65, y: 0.15 },
    ],
  },
  '4-2-3-1': {
    slots: [
      { id: 'GK',   label: 'PO',  position: 'GK',  x: 0.50, y: 0.87 },
      { id: 'LB',   label: 'LI',  position: 'LB',  x: 0.12, y: 0.70 },
      { id: 'CB1',  label: 'DFC', position: 'CB',  x: 0.35, y: 0.72 },
      { id: 'CB2',  label: 'DFC', position: 'CB',  x: 0.65, y: 0.72 },
      { id: 'RB',   label: 'LD',  position: 'RB',  x: 0.88, y: 0.70 },
      { id: 'CDM1', label: 'MCD', position: 'CDM', x: 0.35, y: 0.57 },
      { id: 'CDM2', label: 'MCD', position: 'CDM', x: 0.65, y: 0.57 },
      { id: 'LW',   label: 'EI',  position: 'LW',  x: 0.15, y: 0.33 },
      { id: 'CAM',  label: 'MCO', position: 'CAM', x: 0.50, y: 0.30 },
      { id: 'RW',   label: 'ED',  position: 'RW',  x: 0.85, y: 0.33 },
      { id: 'ST',   label: 'DC',  position: 'ST',  x: 0.50, y: 0.13 },
    ],
  },
  '3-5-2': {
    slots: [
      { id: 'GK',   label: 'PO',  position: 'GK',  x: 0.50, y: 0.87 },
      { id: 'CB1',  label: 'DFC', position: 'CB',  x: 0.20, y: 0.71 },
      { id: 'CB2',  label: 'DFC', position: 'CB',  x: 0.50, y: 0.73 },
      { id: 'CB3',  label: 'DFC', position: 'CB',  x: 0.80, y: 0.71 },
      { id: 'LWB',  label: 'CAI', position: 'LWB', x: 0.08, y: 0.52 },
      { id: 'CDM',  label: 'MCD', position: 'CDM', x: 0.30, y: 0.47 },
      { id: 'CM',   label: 'MC',  position: 'CM',  x: 0.50, y: 0.44 },
      { id: 'CDM2', label: 'MCD', position: 'CDM', x: 0.70, y: 0.47 },
      { id: 'RWB',  label: 'CAD', position: 'RWB', x: 0.92, y: 0.52 },
      { id: 'ST1',  label: 'DC',  position: 'ST',  x: 0.35, y: 0.15 },
      { id: 'ST2',  label: 'DC',  position: 'ST',  x: 0.65, y: 0.15 },
    ],
  },
  '4-1-2-1-2': {
    slots: [
      { id: 'GK',   label: 'PO',  position: 'GK',  x: 0.50, y: 0.87 },
      { id: 'LB',   label: 'LI',  position: 'LB',  x: 0.15, y: 0.70 },
      { id: 'CB1',  label: 'DFC', position: 'CB',  x: 0.38, y: 0.72 },
      { id: 'CB2',  label: 'DFC', position: 'CB',  x: 0.62, y: 0.72 },
      { id: 'RB',   label: 'LD',  position: 'RB',  x: 0.85, y: 0.70 },
      { id: 'CDM',  label: 'MCD', position: 'CDM', x: 0.50, y: 0.58 },
      { id: 'LCM',  label: 'MC',  position: 'CM',  x: 0.25, y: 0.45 },
      { id: 'RCM',  label: 'MC',  position: 'CM',  x: 0.75, y: 0.45 },
      { id: 'CAM',  label: 'MCO', position: 'CAM', x: 0.50, y: 0.32 },
      { id: 'ST1',  label: 'DC',  position: 'ST',  x: 0.33, y: 0.15 },
      { id: 'ST2',  label: 'DC',  position: 'ST',  x: 0.67, y: 0.15 },
    ],
  },
  '4-5-1': {
    slots: [
      { id: 'GK',   label: 'PO',  position: 'GK',  x: 0.50, y: 0.87 },
      { id: 'LB',   label: 'LI',  position: 'LB',  x: 0.12, y: 0.70 },
      { id: 'CB1',  label: 'DFC', position: 'CB',  x: 0.35, y: 0.72 },
      { id: 'CB2',  label: 'DFC', position: 'CB',  x: 0.65, y: 0.72 },
      { id: 'RB',   label: 'LD',  position: 'RB',  x: 0.88, y: 0.70 },
      { id: 'LM',   label: 'MI',  position: 'LM',  x: 0.10, y: 0.47 },
      { id: 'LCM',  label: 'MC',  position: 'CM',  x: 0.30, y: 0.45 },
      { id: 'CM',   label: 'MC',  position: 'CM',  x: 0.50, y: 0.43 },
      { id: 'RCM',  label: 'MC',  position: 'CM',  x: 0.70, y: 0.45 },
      { id: 'RM',   label: 'MD',  position: 'RM',  x: 0.90, y: 0.47 },
      { id: 'ST',   label: 'DC',  position: 'ST',  x: 0.50, y: 0.13 },
    ],
  },
  '5-3-2': {
    slots: [
      { id: 'GK',   label: 'PO',  position: 'GK',  x: 0.50, y: 0.87 },
      { id: 'LWB',  label: 'CAI', position: 'LWB', x: 0.08, y: 0.68 },
      { id: 'CB1',  label: 'DFC', position: 'CB',  x: 0.25, y: 0.72 },
      { id: 'CB2',  label: 'DFC', position: 'CB',  x: 0.50, y: 0.74 },
      { id: 'CB3',  label: 'DFC', position: 'CB',  x: 0.75, y: 0.72 },
      { id: 'RWB',  label: 'CAD', position: 'RWB', x: 0.92, y: 0.68 },
      { id: 'LCM',  label: 'MC',  position: 'CM',  x: 0.25, y: 0.48 },
      { id: 'CM',   label: 'MC',  position: 'CM',  x: 0.50, y: 0.45 },
      { id: 'RCM',  label: 'MC',  position: 'CM',  x: 0.75, y: 0.48 },
      { id: 'ST1',  label: 'DC',  position: 'ST',  x: 0.35, y: 0.15 },
      { id: 'ST2',  label: 'DC',  position: 'ST',  x: 0.65, y: 0.15 },
    ],
  },
  '3-4-3': {
    slots: [
      { id: 'GK',   label: 'PO',  position: 'GK',  x: 0.50, y: 0.87 },
      { id: 'CB1',  label: 'DFC', position: 'CB',  x: 0.20, y: 0.71 },
      { id: 'CB2',  label: 'DFC', position: 'CB',  x: 0.50, y: 0.73 },
      { id: 'CB3',  label: 'DFC', position: 'CB',  x: 0.80, y: 0.71 },
      { id: 'LM',   label: 'MI',  position: 'LM',  x: 0.12, y: 0.50 },
      { id: 'LCM',  label: 'MC',  position: 'CM',  x: 0.37, y: 0.47 },
      { id: 'RCM',  label: 'MC',  position: 'CM',  x: 0.63, y: 0.47 },
      { id: 'RM',   label: 'MD',  position: 'RM',  x: 0.88, y: 0.50 },
      { id: 'LW',   label: 'EI',  position: 'LW',  x: 0.15, y: 0.20 },
      { id: 'ST',   label: 'DC',  position: 'ST',  x: 0.50, y: 0.13 },
      { id: 'RW',   label: 'ED',  position: 'RW',  x: 0.85, y: 0.20 },
    ],
  },
  '4-1-4-1': {
    slots: [
      { id: 'GK',   label: 'PO',  position: 'GK',  x: 0.50, y: 0.87 },
      { id: 'LB',   label: 'LI',  position: 'LB',  x: 0.12, y: 0.70 },
      { id: 'CB1',  label: 'DFC', position: 'CB',  x: 0.35, y: 0.72 },
      { id: 'CB2',  label: 'DFC', position: 'CB',  x: 0.65, y: 0.72 },
      { id: 'RB',   label: 'LD',  position: 'RB',  x: 0.88, y: 0.70 },
      { id: 'CDM',  label: 'MCD', position: 'CDM', x: 0.50, y: 0.57 },
      { id: 'LM',   label: 'MI',  position: 'LM',  x: 0.10, y: 0.42 },
      { id: 'LCM',  label: 'MC',  position: 'CM',  x: 0.33, y: 0.40 },
      { id: 'RCM',  label: 'MC',  position: 'CM',  x: 0.67, y: 0.40 },
      { id: 'RM',   label: 'MD',  position: 'RM',  x: 0.90, y: 0.42 },
      { id: 'ST',   label: 'DC',  position: 'ST',  x: 0.50, y: 0.13 },
    ],
  },
  '4-3-1-2': {
    slots: [
      { id: 'GK',   label: 'PO',  position: 'GK',  x: 0.50, y: 0.87 },
      { id: 'LB',   label: 'LI',  position: 'LB',  x: 0.12, y: 0.70 },
      { id: 'CB1',  label: 'DFC', position: 'CB',  x: 0.35, y: 0.72 },
      { id: 'CB2',  label: 'DFC', position: 'CB',  x: 0.65, y: 0.72 },
      { id: 'RB',   label: 'LD',  position: 'RB',  x: 0.88, y: 0.70 },
      { id: 'LCM',  label: 'MC',  position: 'CM',  x: 0.22, y: 0.52 },
      { id: 'CM',   label: 'MC',  position: 'CM',  x: 0.50, y: 0.50 },
      { id: 'RCM',  label: 'MC',  position: 'CM',  x: 0.78, y: 0.52 },
      { id: 'CAM',  label: 'MCO', position: 'CAM', x: 0.50, y: 0.35 },
      { id: 'ST1',  label: 'DC',  position: 'ST',  x: 0.33, y: 0.15 },
      { id: 'ST2',  label: 'DC',  position: 'ST',  x: 0.67, y: 0.15 },
    ],
  },

  // ── Variantes ────────────────────────────────────────────────────────────

  '4-3-3 (A)': {
    slots: [
      { id: 'GK',   label: 'PO',  position: 'GK',  x: 0.50, y: 0.87 },
      { id: 'LB',   label: 'LI',  position: 'LB',  x: 0.12, y: 0.69 },
      { id: 'CB1',  label: 'DFC', position: 'CB',  x: 0.35, y: 0.71 },
      { id: 'CB2',  label: 'DFC', position: 'CB',  x: 0.65, y: 0.71 },
      { id: 'RB',   label: 'LD',  position: 'RB',  x: 0.88, y: 0.69 },
      { id: 'LCM',  label: 'MC',  position: 'CM',  x: 0.22, y: 0.43 },
      { id: 'CM',   label: 'MC',  position: 'CM',  x: 0.50, y: 0.40 },
      { id: 'RCM',  label: 'MC',  position: 'CM',  x: 0.78, y: 0.43 },
      { id: 'LW',   label: 'EI',  position: 'LW',  x: 0.10, y: 0.14 },
      { id: 'ST',   label: 'DC',  position: 'ST',  x: 0.50, y: 0.08 },
      { id: 'RW',   label: 'ED',  position: 'RW',  x: 0.90, y: 0.14 },
    ],
  },

  '4-3-3 (D)': {
    slots: [
      { id: 'GK',   label: 'PO',  position: 'GK',  x: 0.50, y: 0.87 },
      { id: 'LB',   label: 'LI',  position: 'LB',  x: 0.12, y: 0.70 },
      { id: 'CB1',  label: 'DFC', position: 'CB',  x: 0.35, y: 0.72 },
      { id: 'CB2',  label: 'DFC', position: 'CB',  x: 0.65, y: 0.72 },
      { id: 'RB',   label: 'LD',  position: 'RB',  x: 0.88, y: 0.70 },
      { id: 'LCM',  label: 'MC',  position: 'CM',  x: 0.22, y: 0.53 },
      { id: 'CM',   label: 'MC',  position: 'CM',  x: 0.50, y: 0.50 },
      { id: 'RCM',  label: 'MC',  position: 'CM',  x: 0.78, y: 0.53 },
      { id: 'LW',   label: 'EI',  position: 'LW',  x: 0.12, y: 0.28 },
      { id: 'ST',   label: 'DC',  position: 'ST',  x: 0.50, y: 0.20 },
      { id: 'RW',   label: 'ED',  position: 'RW',  x: 0.88, y: 0.28 },
    ],
  },

  '4-4-2 ♦': {
    slots: [
      { id: 'GK',   label: 'PO',  position: 'GK',  x: 0.50, y: 0.87 },
      { id: 'LB',   label: 'LI',  position: 'LB',  x: 0.12, y: 0.70 },
      { id: 'CB1',  label: 'DFC', position: 'CB',  x: 0.35, y: 0.72 },
      { id: 'CB2',  label: 'DFC', position: 'CB',  x: 0.65, y: 0.72 },
      { id: 'RB',   label: 'LD',  position: 'RB',  x: 0.88, y: 0.70 },
      { id: 'CDM',  label: 'MCD', position: 'CDM', x: 0.50, y: 0.60 },
      { id: 'LCM',  label: 'MC',  position: 'CM',  x: 0.22, y: 0.47 },
      { id: 'RCM',  label: 'MC',  position: 'CM',  x: 0.78, y: 0.47 },
      { id: 'CAM',  label: 'MCO', position: 'CAM', x: 0.50, y: 0.30 },
      { id: 'ST1',  label: 'DC',  position: 'ST',  x: 0.35, y: 0.14 },
      { id: 'ST2',  label: 'DC',  position: 'ST',  x: 0.65, y: 0.14 },
    ],
  },

  '5-4-1': {
    slots: [
      { id: 'GK',   label: 'PO',  position: 'GK',  x: 0.50, y: 0.87 },
      { id: 'LWB',  label: 'CAI', position: 'LWB', x: 0.08, y: 0.68 },
      { id: 'CB1',  label: 'DFC', position: 'CB',  x: 0.25, y: 0.73 },
      { id: 'CB2',  label: 'DFC', position: 'CB',  x: 0.50, y: 0.75 },
      { id: 'CB3',  label: 'DFC', position: 'CB',  x: 0.75, y: 0.73 },
      { id: 'RWB',  label: 'CAD', position: 'RWB', x: 0.92, y: 0.68 },
      { id: 'LM',   label: 'MI',  position: 'LM',  x: 0.15, y: 0.46 },
      { id: 'LCM',  label: 'MC',  position: 'CM',  x: 0.38, y: 0.43 },
      { id: 'RCM',  label: 'MC',  position: 'CM',  x: 0.62, y: 0.43 },
      { id: 'RM',   label: 'MD',  position: 'RM',  x: 0.85, y: 0.46 },
      { id: 'ST',   label: 'DC',  position: 'ST',  x: 0.50, y: 0.15 },
    ],
  },

  '4-1-3-2': {
    slots: [
      { id: 'GK',   label: 'PO',  position: 'GK',  x: 0.50, y: 0.87 },
      { id: 'LB',   label: 'LI',  position: 'LB',  x: 0.12, y: 0.70 },
      { id: 'CB1',  label: 'DFC', position: 'CB',  x: 0.35, y: 0.72 },
      { id: 'CB2',  label: 'DFC', position: 'CB',  x: 0.65, y: 0.72 },
      { id: 'RB',   label: 'LD',  position: 'RB',  x: 0.88, y: 0.70 },
      { id: 'CDM',  label: 'MCD', position: 'CDM', x: 0.50, y: 0.58 },
      { id: 'LCM',  label: 'MC',  position: 'CM',  x: 0.20, y: 0.38 },
      { id: 'CAM',  label: 'MCO', position: 'CAM', x: 0.50, y: 0.34 },
      { id: 'RCM',  label: 'MC',  position: 'CM',  x: 0.80, y: 0.38 },
      { id: 'ST1',  label: 'DC',  position: 'ST',  x: 0.35, y: 0.14 },
      { id: 'ST2',  label: 'DC',  position: 'ST',  x: 0.65, y: 0.14 },
    ],
  },

  '3-4-1-2': {
    slots: [
      { id: 'GK',   label: 'PO',  position: 'GK',  x: 0.50, y: 0.87 },
      { id: 'CB1',  label: 'DFC', position: 'CB',  x: 0.22, y: 0.72 },
      { id: 'CB2',  label: 'DFC', position: 'CB',  x: 0.50, y: 0.73 },
      { id: 'CB3',  label: 'DFC', position: 'CB',  x: 0.78, y: 0.72 },
      { id: 'LM',   label: 'MI',  position: 'LM',  x: 0.10, y: 0.53 },
      { id: 'LCM',  label: 'MC',  position: 'CM',  x: 0.35, y: 0.48 },
      { id: 'RCM',  label: 'MC',  position: 'CM',  x: 0.65, y: 0.48 },
      { id: 'RM',   label: 'MD',  position: 'RM',  x: 0.90, y: 0.53 },
      { id: 'CAM',  label: 'MCO', position: 'CAM', x: 0.50, y: 0.30 },
      { id: 'ST1',  label: 'DC',  position: 'ST',  x: 0.33, y: 0.13 },
      { id: 'ST2',  label: 'DC',  position: 'ST',  x: 0.67, y: 0.13 },
    ],
  },

  '4-2-3-1 (W)': {
    slots: [
      { id: 'GK',   label: 'PO',  position: 'GK',  x: 0.50, y: 0.87 },
      { id: 'LB',   label: 'LI',  position: 'LB',  x: 0.12, y: 0.70 },
      { id: 'CB1',  label: 'DFC', position: 'CB',  x: 0.35, y: 0.72 },
      { id: 'CB2',  label: 'DFC', position: 'CB',  x: 0.65, y: 0.72 },
      { id: 'RB',   label: 'LD',  position: 'RB',  x: 0.88, y: 0.70 },
      { id: 'CDM1', label: 'MCD', position: 'CDM', x: 0.35, y: 0.57 },
      { id: 'CDM2', label: 'MCD', position: 'CDM', x: 0.65, y: 0.57 },
      { id: 'LW',   label: 'EI',  position: 'LW',  x: 0.07, y: 0.30 },
      { id: 'CAM',  label: 'MCO', position: 'CAM', x: 0.50, y: 0.28 },
      { id: 'RW',   label: 'ED',  position: 'RW',  x: 0.93, y: 0.30 },
      { id: 'ST',   label: 'DC',  position: 'ST',  x: 0.50, y: 0.13 },
    ],
  },

  '4-4-1-1': {
    slots: [
      { id: 'GK',   label: 'PO',  position: 'GK',  x: 0.50, y: 0.87 },
      { id: 'LB',   label: 'LI',  position: 'LB',  x: 0.12, y: 0.70 },
      { id: 'CB1',  label: 'DFC', position: 'CB',  x: 0.35, y: 0.72 },
      { id: 'CB2',  label: 'DFC', position: 'CB',  x: 0.65, y: 0.72 },
      { id: 'RB',   label: 'LD',  position: 'RB',  x: 0.88, y: 0.70 },
      { id: 'LM',   label: 'MI',  position: 'LM',  x: 0.10, y: 0.47 },
      { id: 'LCM',  label: 'MC',  position: 'CM',  x: 0.35, y: 0.44 },
      { id: 'RCM',  label: 'MC',  position: 'CM',  x: 0.65, y: 0.44 },
      { id: 'RM',   label: 'MD',  position: 'RM',  x: 0.90, y: 0.47 },
      { id: 'CF',   label: 'SD',  position: 'CAM', x: 0.50, y: 0.27 },
      { id: 'ST',   label: 'DC',  position: 'ST',  x: 0.50, y: 0.12 },
    ],
  },

  '4-3-2-1': {
    slots: [
      { id: 'GK',   label: 'PO',  position: 'GK',  x: 0.50, y: 0.87 },
      { id: 'LB',   label: 'LI',  position: 'LB',  x: 0.12, y: 0.70 },
      { id: 'CB1',  label: 'DFC', position: 'CB',  x: 0.35, y: 0.72 },
      { id: 'CB2',  label: 'DFC', position: 'CB',  x: 0.65, y: 0.72 },
      { id: 'RB',   label: 'LD',  position: 'RB',  x: 0.88, y: 0.70 },
      { id: 'LCM',  label: 'MC',  position: 'CM',  x: 0.22, y: 0.52 },
      { id: 'CM',   label: 'MC',  position: 'CM',  x: 0.50, y: 0.49 },
      { id: 'RCM',  label: 'MC',  position: 'CM',  x: 0.78, y: 0.52 },
      { id: 'LAM',  label: 'MCO', position: 'CAM', x: 0.33, y: 0.29 },
      { id: 'RAM',  label: 'MCO', position: 'CAM', x: 0.67, y: 0.29 },
      { id: 'ST',   label: 'DC',  position: 'ST',  x: 0.50, y: 0.12 },
    ],
  },

  '5-2-2-1': {
    slots: [
      { id: 'GK',   label: 'PO',  position: 'GK',  x: 0.50, y: 0.87 },
      { id: 'LWB',  label: 'CAI', position: 'LWB', x: 0.07, y: 0.67 },
      { id: 'CB1',  label: 'DFC', position: 'CB',  x: 0.25, y: 0.73 },
      { id: 'CB2',  label: 'DFC', position: 'CB',  x: 0.50, y: 0.75 },
      { id: 'CB3',  label: 'DFC', position: 'CB',  x: 0.75, y: 0.73 },
      { id: 'RWB',  label: 'CAD', position: 'RWB', x: 0.93, y: 0.67 },
      { id: 'CDM1', label: 'MCD', position: 'CDM', x: 0.33, y: 0.53 },
      { id: 'CDM2', label: 'MCD', position: 'CDM', x: 0.67, y: 0.53 },
      { id: 'CAM1', label: 'MCO', position: 'CAM', x: 0.30, y: 0.32 },
      { id: 'CAM2', label: 'MCO', position: 'CAM', x: 0.70, y: 0.32 },
      { id: 'ST',   label: 'DC',  position: 'ST',  x: 0.50, y: 0.12 },
    ],
  },
};
