// Coordenadas normalizadas: x (0=izq, 1=der), y (0=arriba/rival, 1=abajo/portería propia)
export const FORMATIONS = {
  '4-3-3': {
    slots: [
      { id: 'GK',   label: 'PO',  position: 'GK',  x: 0.50, y: 0.87 },
      { id: 'LB',   label: 'LD',  position: 'LB',  x: 0.12, y: 0.69 },
      { id: 'CB1',  label: 'DFC', position: 'CB',  x: 0.35, y: 0.71 },
      { id: 'CB2',  label: 'DFC', position: 'CB',  x: 0.65, y: 0.71 },
      { id: 'RB',   label: 'LD',  position: 'RB',  x: 0.88, y: 0.69 },
      { id: 'LCM',  label: 'MC',  position: 'CM',  x: 0.22, y: 0.48 },
      { id: 'CM',   label: 'MC',  position: 'CM',  x: 0.50, y: 0.45 },
      { id: 'RCM',  label: 'MC',  position: 'CM',  x: 0.78, y: 0.48 },
      { id: 'LW',   label: 'EI',  position: 'LW',  x: 0.12, y: 0.20 },
      { id: 'ST',   label: 'DC',  position: 'ST',  x: 0.50, y: 0.13 },
      { id: 'RW',   label: 'ED',  position: 'RW',  x: 0.88, y: 0.20 },
    ],
  },
  '4-4-2': {
    slots: [
      { id: 'GK',   label: 'PO',  position: 'GK',  x: 0.50, y: 0.87 },
      { id: 'LB',   label: 'LD',  position: 'LB',  x: 0.12, y: 0.70 },
      { id: 'CB1',  label: 'DFC', position: 'CB',  x: 0.35, y: 0.72 },
      { id: 'CB2',  label: 'DFC', position: 'CB',  x: 0.65, y: 0.72 },
      { id: 'RB',   label: 'LD',  position: 'RB',  x: 0.88, y: 0.70 },
      { id: 'LM',   label: 'ME',  position: 'LM',  x: 0.12, y: 0.50 },
      { id: 'LCM',  label: 'MC',  position: 'CM',  x: 0.37, y: 0.47 },
      { id: 'RCM',  label: 'MC',  position: 'CM',  x: 0.63, y: 0.47 },
      { id: 'RM',   label: 'ME',  position: 'RM',  x: 0.88, y: 0.50 },
      { id: 'ST1',  label: 'DC',  position: 'ST',  x: 0.35, y: 0.15 },
      { id: 'ST2',  label: 'DC',  position: 'ST',  x: 0.65, y: 0.15 },
    ],
  },
  '4-2-3-1': {
    slots: [
      { id: 'GK',   label: 'PO',  position: 'GK',  x: 0.50, y: 0.87 },
      { id: 'LB',   label: 'LD',  position: 'LB',  x: 0.12, y: 0.70 },
      { id: 'CB1',  label: 'DFC', position: 'CB',  x: 0.35, y: 0.72 },
      { id: 'CB2',  label: 'DFC', position: 'CB',  x: 0.65, y: 0.72 },
      { id: 'RB',   label: 'LD',  position: 'RB',  x: 0.88, y: 0.70 },
      { id: 'CDM1', label: 'MCD', position: 'CDM', x: 0.35, y: 0.57 },
      { id: 'CDM2', label: 'MCD', position: 'CDM', x: 0.65, y: 0.57 },
      { id: 'LW',   label: 'EI',  position: 'LW',  x: 0.15, y: 0.33 },
      { id: 'CAM',  label: 'CAM', position: 'CAM', x: 0.50, y: 0.30 },
      { id: 'RW',   label: 'ED',  position: 'RW',  x: 0.85, y: 0.33 },
      { id: 'ST',   label: 'DC',  position: 'ST',  x: 0.50, y: 0.13 },
    ],
  },
  '3-5-2': {
    slots: [
      { id: 'GK',   label: 'PO',  position: 'GK',  x: 0.50, y: 0.87 },
      { id: 'CB1',  label: 'DFC', position: 'CB',  x: 0.20, y: 0.71 },
      { id: 'CB2',  label: 'DFC', position: 'CB',  x: 0.50, y: 0.73 },
      { id: 'CB3',  label: 'DFC', position: 'CB',  x: 0.80, y: 0.71 },
      { id: 'LWB',  label: 'CAI', position: 'LWB', x: 0.08, y: 0.52 },
      { id: 'CDM',  label: 'MCD', position: 'CDM', x: 0.30, y: 0.47 },
      { id: 'CM',   label: 'MC',  position: 'CM',  x: 0.50, y: 0.44 },
      { id: 'CDM2', label: 'MCD', position: 'CDM', x: 0.70, y: 0.47 },
      { id: 'RWB',  label: 'CAD', position: 'RWB', x: 0.92, y: 0.52 },
      { id: 'ST1',  label: 'DC',  position: 'ST',  x: 0.35, y: 0.15 },
      { id: 'ST2',  label: 'DC',  position: 'ST',  x: 0.65, y: 0.15 },
    ],
  },
};
